
version: '3'

services:
  pg-master:
    build: '.'
    image: 'danieldent/postgres-replication'
    restart: 'always'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      PGDATA: '/data/9.6'
    volumes:
     - '/data'
    expose:
     - '5432'

  pg-slave:
    build: '.'
    image: 'danieldent/postgres-replication'
    restart: 'always'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      PGDATA: '/data'
      REPLICATE_FROM: 'pg-master'
    volumes:
     - '/data/9.6'
    expose:
     - '5432'
    links:
     - 'pg-master'
